apiVersion: v1
kind: PersistentVolume
metadata:
  name: python-sf-api-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /root
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: python-sf-api-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: python-sf-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-sf-api
  template:
    metadata:
      labels:
        app: python-sf-api
    spec:
      containers:
        - name: python-sf-api
          image: python-sf-api:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: python-sf-api-volume
              mountPath: /root
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: python-sf-api-volume
          persistentVolumeClaim:
            claimName: python-sf-api-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: my-python
spec:
ports:
  - name: http-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
selector:
  app: python-sf-api